version: "3.1"

services:
  mysql:
    container_name: "mysql"
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./migrations/20222010_up.sql:/docker-entrypoint-initdb.d/20222010_up.sql
      - ./migrations/conf.d:/etc/mysql/conf.d
    restart: always
    expose:
      - 3306

  server:
    container_name: "server"
    image: server
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    restart: always
    links:
      - "mysql"

  nginx:
    container_name: "nginx-rust"
    image: "nginx:latest"
    ports:
      - "80:80"
    links:
      - server
    depends_on:
      - server
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
